"use strict";
require("dotenv").config();
const path=require("path");
const express=require("express");
const {query,transaction}=require("./db");
const app=express(),PORT=process.env.PORT||3000;
app.use(express.json({limit:"2mb"}));
app.use(express.static(path.join(__dirname,"public")));

app.get("/api/health",async(_q,r)=>{try{await query("SELECT 1");r.json({ok:true,database:"connected"})}catch(e){r.status(500).json({ok:false,error:e.message})}});
app.get("/api/models",async(_q,r)=>{try{const x=await query(`SELECT id,model_code AS "modelCode",model_name AS "modelName" FROM models WHERE is_active=TRUE ORDER BY model_code`);r.json({models:x.rows})}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/models",async(q,r)=>{const code=String(q.body?.modelCode||"").trim(),name=String(q.body?.modelName||code).trim();if(!code)return r.status(400).json({error:"modelCode is required"});try{const x=await query(`INSERT INTO models(model_code,model_name) VALUES($1,$2) RETURNING id,model_code AS "modelCode",model_name AS "modelName"`,[code,name]);r.status(201).json({model:x.rows[0]})}catch(e){r.status(e.code==="23505"?409:500).json({error:e.code==="23505"?"Model already exists":e.message})}});
app.get("/api/models/:id/parts",async(q,r)=>{try{const x=await query(`SELECT id,model_id AS "modelId",part_code AS "partCode",part_name AS "partName",machine_code AS "machineCode" FROM parts WHERE model_id=$1 AND is_active=TRUE ORDER BY part_code`,[q.params.id]);r.json({parts:x.rows})}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/parts",async(q,r)=>{const modelId=+q.body?.modelId,partCode=String(q.body?.partCode||"").trim(),partName=String(q.body?.partName||partCode).trim(),machine=String(q.body?.machineCode||"").trim()||null;if(!modelId||!partCode)return r.status(400).json({error:"modelId and partCode are required"});try{const x=await query(`INSERT INTO parts(model_id,part_code,part_name,machine_code) VALUES($1,$2,$3,$4) RETURNING id,model_id AS "modelId",part_code AS "partCode",part_name AS "partName",machine_code AS "machineCode"`,[modelId,partCode,partName,machine]);r.status(201).json({part:x.rows[0]})}catch(e){r.status(e.code==="23505"?409:500).json({error:e.code==="23505"?"Part already exists in this Model":e.message})}});
app.get("/api/parts/:id/template",async(q,r)=>{try{const p=await query(`SELECT p.id,p.part_code AS "partCode",p.part_name AS "partName",p.machine_code AS "machineCode",m.id AS "modelId",m.model_code AS "modelCode",m.model_name AS "modelName" FROM parts p JOIN models m ON m.id=p.model_id WHERE p.id=$1 AND p.is_active=TRUE AND m.is_active=TRUE`,[q.params.id]);if(!p.rows.length)return r.status(404).json({error:"Part not found"});const x=await query(`SELECT id,item_no AS "itemNo",condition_group AS "conditionGroup",topic,standard_value AS "standardValue",input_type AS "inputType",unit,is_required AS "isRequired" FROM condition_template_items WHERE part_id=$1 AND is_active=TRUE ORDER BY item_no`,[q.params.id]);r.json({part:p.rows[0],items:x.rows})}catch(e){r.status(500).json({error:e.message})}});
app.put("/api/parts/:id/template",async(q,r)=>{const partId=+q.params.id,items=Array.isArray(q.body?.items)?q.body.items:[];if(!partId||!items.length)return r.status(400).json({error:"partId and items are required"});try{await transaction(async c=>{await c.query("DELETE FROM condition_template_items WHERE part_id=$1",[partId]);for(const i of items)await c.query(`INSERT INTO condition_template_items(part_id,item_no,condition_group,topic,standard_value,input_type,unit,is_required,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,TRUE)`,[partId,+i.itemNo,String(i.conditionGroup||"").trim(),String(i.topic||"").trim(),String(i.standardValue||"").trim()||null,String(i.inputType||"text").trim(),String(i.unit||"").trim()||null,i.isRequired!==false])});r.json({ok:true,itemCount:items.length})}catch(e){r.status(500).json({error:e.message})}});

app.post("/api/records",async(q,r)=>{
  const b=q.body||{},modelId=+b.modelId,partId=+b.partId,items=Array.isArray(b.items)?b.items:[];
  if(!modelId||!partId||!items.length)return r.status(400).json({error:"modelId, partId and items are required"});
  try{const out=await transaction(async c=>{
    const p=await c.query(`SELECT p.*,m.model_code,m.model_name FROM parts p JOIN models m ON m.id=p.model_id WHERE p.id=$1 AND p.model_id=$2`,[partId,modelId]);
    if(!p.rows.length){const e=new Error("Model / Part not found");e.status=404;throw e}
    const t=await c.query(`SELECT id,item_no,condition_group,topic,standard_value,unit,is_required FROM condition_template_items WHERE part_id=$1 AND is_active=TRUE ORDER BY item_no`,[partId]);
    const map=new Map(items.map(i=>[+i.itemNo,i])),missing=t.rows.filter(i=>i.is_required&&!String(map.get(+i.item_no)?.actualValue??"").trim());
    if(missing.length){const e=new Error(`Missing Condition: ${missing.map(i=>i.item_no).join(", ")}`);e.status=400;throw e}
    const stamp=new Date().toISOString().replace(/\D/g,"").slice(0,14),no=`COND-${stamp}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
    const h=await c.query(`INSERT INTO condition_records(record_no,model_id,part_id,record_date,recorded_at,machine_code,shift,recorder_name,recorder_code,note) VALUES($1,$2,$3,COALESCE($4::date,CURRENT_DATE),NOW(),$5,$6,$7,$8,$9) RETURNING id,record_no AS "recordNo",record_date AS "recordDate",recorded_at AS "recordedAt"`,[no,modelId,partId,b.recordDate||null,String(b.machineCode||p.rows[0].machine_code||"").trim()||null,String(b.shift||"").trim()||null,String(b.recorderName||"").trim()||null,String(b.recorderCode||"").trim()||null,String(b.note||"").trim()||null]);
    for(const i of t.rows){const v=map.get(+i.item_no)||{};await c.query(`INSERT INTO condition_record_items(record_id,template_item_id,item_no,condition_group,topic,standard_value,actual_value,validation_status,validation_message,unit) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[h.rows[0].id,i.id,i.item_no,i.condition_group,i.topic,i.standard_value,String(v.actualValue??"").trim()||null,String(v.validationStatus||"").trim()||null,String(v.validationMessage||"").trim()||null,i.unit])}
    return{...h.rows[0],modelCode:p.rows[0].model_code,modelName:p.rows[0].model_name,partCode:p.rows[0].part_code,partName:p.rows[0].part_name,itemCount:t.rows.length};
  });r.status(201).json({ok:true,record:out})}catch(e){r.status(e.status||500).json({error:e.message})}
});

app.get("/api/records",async(q,r)=>{const modelId=q.query.modelId?+q.query.modelId:null,partId=q.query.partId?+q.query.partId:null,from=q.query.dateFrom||null,to=q.query.dateTo||null,s=String(q.query.q||"").trim();try{const x=await query(`SELECT r.id,r.record_no AS "recordNo",r.record_date AS "recordDate",r.recorded_at AS "recordedAt",r.machine_code AS "machineCode",r.shift,r.recorder_name AS "recorderName",r.recorder_code AS "recorderCode",m.id AS "modelId",m.model_code AS "modelCode",m.model_name AS "modelName",p.id AS "partId",p.part_code AS "partCode",p.part_name AS "partName",COUNT(i.id)::int AS "itemCount" FROM condition_records r JOIN models m ON m.id=r.model_id JOIN parts p ON p.id=r.part_id LEFT JOIN condition_record_items i ON i.record_id=r.id WHERE($1::bigint IS NULL OR r.model_id=$1)AND($2::bigint IS NULL OR r.part_id=$2)AND($3::date IS NULL OR r.record_date>=$3)AND($4::date IS NULL OR r.record_date<=$4)AND($5='' OR m.model_code ILIKE '%'||$5||'%' OR p.part_code ILIKE '%'||$5||'%' OR COALESCE(r.recorder_name,'') ILIKE '%'||$5||'%' OR COALESCE(r.recorder_code,'') ILIKE '%'||$5||'%') GROUP BY r.id,m.id,p.id ORDER BY r.recorded_at DESC LIMIT 500`,[modelId,partId,from,to,s]);r.json({records:x.rows})}catch(e){r.status(500).json({error:e.message})}});
app.get("/api/records/:id",async(q,r)=>{try{const h=await query(`SELECT r.id,r.record_no AS "recordNo",r.record_date AS "recordDate",r.recorded_at AS "recordedAt",r.machine_code AS "machineCode",r.shift,r.recorder_name AS "recorderName",r.recorder_code AS "recorderCode",r.note,m.id AS "modelId",m.model_code AS "modelCode",m.model_name AS "modelName",p.id AS "partId",p.part_code AS "partCode",p.part_name AS "partName" FROM condition_records r JOIN models m ON m.id=r.model_id JOIN parts p ON p.id=r.part_id WHERE r.id=$1`,[q.params.id]);if(!h.rows.length)return r.status(404).json({error:"Condition record not found"});const x=await query(`SELECT item_no AS "itemNo",condition_group AS "conditionGroup",topic,standard_value AS "standardValue",actual_value AS "actualValue",validation_status AS "validationStatus",validation_message AS "validationMessage",unit FROM condition_record_items WHERE record_id=$1 ORDER BY item_no`,[q.params.id]);r.json({record:h.rows[0],items:x.rows})}catch(e){r.status(500).json({error:e.message})}});

app.get("*",(_q,r)=>r.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log(`Online Condition Record running on http://localhost:${PORT}`));
