"use strict";
const fs=require("fs"),path=require("path");
const {pool,transaction}=require("../db");
const ITEMS=[["Mold Temperature","Cavity","22-32 °C",1],["Mold Temperature","Core","22-32 °C",1],["Cylinder Temperature","N1","210 °C ±10",1],["Cylinder Temperature","N2","210 °C ±10",1],["Cylinder Temperature","C1","220 °C ±10",1],["Cylinder Temperature","C2","210 °C ±10",1],["Cylinder Temperature","C3","200 °C ±10",1],["Cylinder Temperature","C4","190 °C ±10",1],["Cylinder Temperature","C5","ไม่ได้ใช้งาน",0],["Valve Gate","Valve 1","0.5 / 9.0 sec",1],["Valve Gate","Valve 2","0.9 / 9.3 sec",1],["Valve Gate","Valve 3","ไม่ได้ใช้งาน",0],["Valve Gate","Valve 4","ไม่ได้ใช้งาน",0],["Valve Gate","Valve 5","ไม่ได้ใช้งาน",0],["Valve Gate","Valve 6","ไม่ได้ใช้งาน",0],["Injection Pressure","Injection Max","74.3 MPa ±5",1],["Clamp Pressure","Clamp Max","830 ton ±30",1],["Time","Injection Time","3.24 sec ±0.5",1],["Time","Cure / Cooling Time","15 sec ±5",1],["Time","Plast Time","10.59 sec ±3",1],["Time","Cycle Time","41.3 sec ±3",1],["Cushion","Cushion Position","8 mm ±2",1],["Mold Cooling","Cavity Set","24 °C",1],["Mold Cooling","Cavity Display","19-29 °C",1],["Mold Cooling","Core Set","24 °C",1],["Mold Cooling","Core Display","19-29 °C",1],["Mold Temp Control Box","Zone 1","220 °C",1],["Mold Temp Control Box","Zone 2","220 °C",1],["Mold Temp Control Box","Zone 3","220 °C",1],["Hot Runner","Zone 1","210 °C",1],["Hot Runner","Zone 2","210 °C",1],["Hot Runner","Zone 3","210 °C",1],["Hot Runner","Zone 4","210 °C",1],["Hot Runner","Zone 5","210 °C",1],["Hot Runner","Zone 6","210 °C",1],["Dryer","Drying Temperature","90 °C ±10",1],["Material","Recycle Material","ใช้ = 1 / ไม่ใช้ = 0",1]];
(async()=>{
  await pool.query(fs.readFileSync(path.join(__dirname,"..","sql","schema.sql"),"utf8"));
  await transaction(async c=>{
    const m=await c.query(`INSERT INTO models(model_code,model_name) VALUES($1,$2) ON CONFLICT(model_code) DO UPDATE SET model_name=EXCLUDED.model_name,updated_at=NOW() RETURNING id`,["RG01","RG01"]);
    const p=await c.query(`INSERT INTO parts(model_id,part_code,part_name,machine_code) VALUES($1,$2,$3,$4) ON CONFLICT(model_id,part_code) DO UPDATE SET part_name=EXCLUDED.part_name,machine_code=EXCLUDED.machine_code,updated_at=NOW() RETURNING id`,[m.rows[0].id,"MC16-CONDITION","Check Sheet Condition","MC16"]);
    const id=p.rows[0].id,count=+(await c.query("SELECT COUNT(*)::int AS count FROM condition_template_items WHERE part_id=$1",[id])).rows[0].count;
    if(!count){let n=0;for(const [g,t,s,req] of ITEMS){n++;await c.query(`INSERT INTO condition_template_items(part_id,item_no,condition_group,topic,standard_value,input_type,unit,is_required,is_active) VALUES($1,$2,$3,$4,$5,'text',NULL,$6,TRUE)`,[id,n,g,t,s,!!req])}console.log(`Seeded ${n} Condition items`)}else console.log(`Condition template already exists (${count} items). Seed skipped.`);
  });
  await pool.end();
})().catch(async e=>{console.error(e);await pool.end();process.exit(1)});
